# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NomatronConnectivityAgent < Formula
  desc "Nomatron Connectivity Agent."
  homepage "https://get.nomatron.io"
  version "0.1.0-rc.35"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nomatronio/nomatron-releases/releases/download/v0.1.0-rc.35/nomatron-connectivity-agent_0.1.0-rc.35_darwin_amd64.zip"
      sha256 "fe38b11b1c6cbe4cd609e5f090cf6a781066963897d50027ca4a0e23736b6f9a"

      define_method(:install) do
        bin.install "nomatron-connectivity-agent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nomatronio/nomatron-releases/releases/download/v0.1.0-rc.35/nomatron-connectivity-agent_0.1.0-rc.35_darwin_arm64.zip"
      sha256 "68727befdcfa3242893a31c22c2deb1c58883a2877acde2701646de8534361c0"

      define_method(:install) do
        bin.install "nomatron-connectivity-agent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nomatronio/nomatron-releases/releases/download/v0.1.0-rc.35/nomatron-connectivity-agent_0.1.0-rc.35_linux_amd64.tar.gz"
      sha256 "8f17310f11a7df487100bcad86f5ddb47c9da483011ea98da1e5a7abb50e9e39"
      define_method(:install) do
        bin.install "nomatron-connectivity-agent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nomatronio/nomatron-releases/releases/download/v0.1.0-rc.35/nomatron-connectivity-agent_0.1.0-rc.35_linux_arm64.tar.gz"
      sha256 "f3da56bab6974f7ee6e3c69d370c31557aed26a153b66382693d3050330df9d8"
      define_method(:install) do
        bin.install "nomatron-connectivity-agent"
      end
    end
  end

  test do
    system "#{bin}/nomatron-connectivity-agent", "-h"
  end
end
