# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NomatronAgent < Formula
  desc "Nomatron network agent."
  homepage "https://get.nomatron.io"
  version "0.1.0-rc.10"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nomatronio/nomatron-releases/releases/download/v0.1.0-rc.10/nomatron-agent_0.1.0-rc.10_darwin_amd64.zip"
      sha256 "b98c7ee34420b6a84e0dbcacf935c4c34a9826140960bb78e9f955f795873bb0"

      define_method(:install) do
        bin.install "nomatron-agent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nomatronio/nomatron-releases/releases/download/v0.1.0-rc.10/nomatron-agent_0.1.0-rc.10_darwin_arm64.zip"
      sha256 "d59bcb834ba0533bfd9139c9a3f957532bddf4723ecb37c51b886ae41dc2bb94"

      define_method(:install) do
        bin.install "nomatron-agent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nomatronio/nomatron-releases/releases/download/v0.1.0-rc.10/nomatron-agent_0.1.0-rc.10_linux_amd64.tar.gz"
      sha256 "cfc33393de1cf63673b17188629ffefb38ad889e216a1f740d50c7381666a708"
      define_method(:install) do
        bin.install "nomatron-agent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nomatronio/nomatron-releases/releases/download/v0.1.0-rc.10/nomatron-agent_0.1.0-rc.10_linux_arm64.tar.gz"
      sha256 "4afc1145e6c0a027316b46825d3f05e3db3f96888480693681e7640da21a80a5"
      define_method(:install) do
        bin.install "nomatron-agent"
      end
    end
  end

  test do
    system "#{bin}/nomatron-agent", "-h"
  end
end
