# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NomatronHostAgent < Formula
  desc "Nomatron Application Networking Host Agent."
  homepage "https://get.nomatron.io"
  version "0.1.0-rc.49"
  license "Proprietary"
  depends_on :linux

  if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
    url "https://github.com/nomatronio/nomatron-releases/releases/download/v0.1.0-rc.49/nomatron-host-agent_0.1.0-rc.49_linux_amd64.tar.gz"
    sha256 "cb8944f15ca038895e719dc3b6aceda78613007869159e5a4f7f2df7f8b3bbf8"
    define_method(:install) do
      bin.install "nomatron-host-agent"
    end
  end
  if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/nomatronio/nomatron-releases/releases/download/v0.1.0-rc.49/nomatron-host-agent_0.1.0-rc.49_linux_arm64.tar.gz"
    sha256 "c061d3d34d516c5f01d6851bf00bc483db05b6ef15fd7fe0f511cfc2da678a1e"
    define_method(:install) do
      bin.install "nomatron-host-agent"
    end
  end

  test do
    system "#{bin}/nomatron-host-agent", "-version"
  end
end
