# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nomatron < Formula
  desc "Nomatron Server CLI."
  homepage "https://get.nomatron.io"
  version "0.1.0-rc.34"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nomatronio/nomatron-releases/releases/download/v0.1.0-rc.34/nomatron_0.1.0-rc.34_darwin_amd64.zip"
      sha256 "b885d9deb42c3f80ee34d142438215bf8ec2f4298446045cbad4fc4c61ac94d0"

      define_method(:install) do
        bin.install "nomatron"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nomatronio/nomatron-releases/releases/download/v0.1.0-rc.34/nomatron_0.1.0-rc.34_darwin_arm64.zip"
      sha256 "14e26a16bf38fcf49867a8293254205f35cb9caec5eba8bf8612dfeb37bb7b08"

      define_method(:install) do
        bin.install "nomatron"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nomatronio/nomatron-releases/releases/download/v0.1.0-rc.34/nomatron_0.1.0-rc.34_linux_amd64.tar.gz"
      sha256 "87d0ddfe0781816419d46e78315886e712ec442aad670abc0d98bcc5804a26bf"
      define_method(:install) do
        bin.install "nomatron"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nomatronio/nomatron-releases/releases/download/v0.1.0-rc.34/nomatron_0.1.0-rc.34_linux_arm64.tar.gz"
      sha256 "76dcf352aa23f9738912348740be4f604e0aa12fcab6e052d37076abf91b9a13"
      define_method(:install) do
        bin.install "nomatron"
      end
    end
  end

  test do
    system "#{bin}/nomatron", "version"
  end
end
