# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nomatron < Formula
  desc "Nomatron management platform CLI and server."
  homepage "https://get.nomatron.io"
  version "0.1.0-rc.8"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nomatronio/nomatron-releases/releases/download/v0.1.0-rc.8/nomatron_0.1.0-rc.8_darwin_amd64.zip"
      sha256 "986322c718c226cfb1cc9e388bdcdbf765a7d7cae2b4e4cfe512ddb737be569a"

      define_method(:install) do
        bin.install "nomatron"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nomatronio/nomatron-releases/releases/download/v0.1.0-rc.8/nomatron_0.1.0-rc.8_darwin_arm64.zip"
      sha256 "0ebb69c77599876489571a0520e29a473132fc805009a51a7a2c4e33c0a4cd39"

      define_method(:install) do
        bin.install "nomatron"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nomatronio/nomatron-releases/releases/download/v0.1.0-rc.8/nomatron_0.1.0-rc.8_linux_amd64.tar.gz"
      sha256 "50edb6dcfc0dad201a3593557bde79779aff4dcaf2a535d34a57b03ceaf6dc02"
      define_method(:install) do
        bin.install "nomatron"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nomatronio/nomatron-releases/releases/download/v0.1.0-rc.8/nomatron_0.1.0-rc.8_linux_arm64.tar.gz"
      sha256 "2add03a2e9f882819ae8cecd327d4beec3aa9d27c0ad591b804a9b1999bc2336"
      define_method(:install) do
        bin.install "nomatron"
      end
    end
  end

  test do
    system "#{bin}/nomatron", "version"
  end
end
