# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NomatronConnectivityAgent < Formula
  desc "Nomatron Connectivity Agent."
  homepage "https://get.nomatron.io"
  version "0.1.0-rc.29"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nomatronio/nomatron-releases/releases/download/v0.1.0-rc.29/nomatron-connectivity-agent_0.1.0-rc.29_darwin_amd64.zip"
      sha256 "ba482dbf2f2efcc4d63d6cea07c044df7ebcc297db4a82d0ef033831b5febdec"

      define_method(:install) do
        bin.install "nomatron-connectivity-agent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nomatronio/nomatron-releases/releases/download/v0.1.0-rc.29/nomatron-connectivity-agent_0.1.0-rc.29_darwin_arm64.zip"
      sha256 "b591586f634b973f6fc8f4f41d809c4deb2d310c76669344e94153f9d12d2660"

      define_method(:install) do
        bin.install "nomatron-connectivity-agent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nomatronio/nomatron-releases/releases/download/v0.1.0-rc.29/nomatron-connectivity-agent_0.1.0-rc.29_linux_amd64.tar.gz"
      sha256 "50653030ae9ae06db0cc147f9dadd10237dea91071cdd28ce7314621a6308dc3"
      define_method(:install) do
        bin.install "nomatron-connectivity-agent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nomatronio/nomatron-releases/releases/download/v0.1.0-rc.29/nomatron-connectivity-agent_0.1.0-rc.29_linux_arm64.tar.gz"
      sha256 "c4096d4c92c8a7a1be126c57e3b3821427ce1395d19d3f9869baf2864010ed29"
      define_method(:install) do
        bin.install "nomatron-connectivity-agent"
      end
    end
  end

  test do
    system "#{bin}/nomatron-connectivity-agent", "-h"
  end
end
