# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NomatronConnectivityAgent < Formula
  desc "Nomatron Connectivity Agent."
  homepage "https://get.nomatron.io"
  version "0.1.0-rc.80"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nomatronio/nomatron-releases/releases/download/v0.1.0-rc.80/nomatron-connectivity-agent_0.1.0-rc.80_darwin_amd64.zip"
      sha256 "b205ba389aa64d4d6b2f669fc4158ac841c0b971d769a98ef989e0dae4c18cab"

      define_method(:install) do
        bin.install "nomatron-connectivity-agent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nomatronio/nomatron-releases/releases/download/v0.1.0-rc.80/nomatron-connectivity-agent_0.1.0-rc.80_darwin_arm64.zip"
      sha256 "1ede48385d36a2bbe365adacbe6ddcb72f92e30aedab28e3fec00f8413127be3"

      define_method(:install) do
        bin.install "nomatron-connectivity-agent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nomatronio/nomatron-releases/releases/download/v0.1.0-rc.80/nomatron-connectivity-agent_0.1.0-rc.80_linux_amd64.tar.gz"
      sha256 "96256e67a9b82dfbc730c4f636aba8a7811c3e3c6eaf4acf934b079713f73a01"
      define_method(:install) do
        bin.install "nomatron-connectivity-agent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nomatronio/nomatron-releases/releases/download/v0.1.0-rc.80/nomatron-connectivity-agent_0.1.0-rc.80_linux_arm64.tar.gz"
      sha256 "b9efe772c19f4e3e3dfcd0be11c25e68499bee588b0efc45cefdb317b2766f0b"
      define_method(:install) do
        bin.install "nomatron-connectivity-agent"
      end
    end
  end

  test do
    system "#{bin}/nomatron-connectivity-agent", "-h"
  end
end
