# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NomatronAgent < Formula
  desc "Nomatron network agent."
  homepage "https://get.nomatron.io"
  version "0.1.0-rc.8"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nomatronio/nomatron-releases/releases/download/v0.1.0-rc.8/nomatron-agent_0.1.0-rc.8_darwin_amd64.zip"
      sha256 "3d984e8bcdf9479eef780930b218af0ab0ee514c2a8f3476daac10dd4c00a226"

      define_method(:install) do
        bin.install "nomatron-agent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nomatronio/nomatron-releases/releases/download/v0.1.0-rc.8/nomatron-agent_0.1.0-rc.8_darwin_arm64.zip"
      sha256 "4c164535aa7ac59241f8810909526cc651053d19154fa2cba74f098dd47788fd"

      define_method(:install) do
        bin.install "nomatron-agent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nomatronio/nomatron-releases/releases/download/v0.1.0-rc.8/nomatron-agent_0.1.0-rc.8_linux_amd64.tar.gz"
      sha256 "26fa5e7bbb61a97a2ef74735ce19f8ad03014cdfb6b02d8bd8e70c4643a44a00"
      define_method(:install) do
        bin.install "nomatron-agent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nomatronio/nomatron-releases/releases/download/v0.1.0-rc.8/nomatron-agent_0.1.0-rc.8_linux_arm64.tar.gz"
      sha256 "3dfd6faf24c47b10b98546089b93618cec324a49ef629b3c2b98e57c8de9666c"
      define_method(:install) do
        bin.install "nomatron-agent"
      end
    end
  end

  test do
    system "#{bin}/nomatron-agent", "-h"
  end
end
