# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NomatronAgent < Formula
  desc "Nomatron network agent."
  homepage "https://get.nomatron.io"
  version "0.1.0-rc.15"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nomatronio/nomatron-releases/releases/download/v0.1.0-rc.15/nomatron-agent_0.1.0-rc.15_darwin_amd64.zip"
      sha256 "8064e0ae71a781e60764189555708d10c89d85b850be7affa9114c99302fbeeb"

      define_method(:install) do
        bin.install "nomatron-agent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nomatronio/nomatron-releases/releases/download/v0.1.0-rc.15/nomatron-agent_0.1.0-rc.15_darwin_arm64.zip"
      sha256 "cb7a2184b81f76e95e367c861b003da03b46bd0ff7ff759c3d152d89136ded27"

      define_method(:install) do
        bin.install "nomatron-agent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nomatronio/nomatron-releases/releases/download/v0.1.0-rc.15/nomatron-agent_0.1.0-rc.15_linux_amd64.tar.gz"
      sha256 "c11152a968def862acd22b884de819628c99c03677fa63d0e32b81e064b7dc30"
      define_method(:install) do
        bin.install "nomatron-agent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nomatronio/nomatron-releases/releases/download/v0.1.0-rc.15/nomatron-agent_0.1.0-rc.15_linux_arm64.tar.gz"
      sha256 "b1e557c14eb6a8f792b04524a46f10f5254080aacff1f8fd48580b3b462856a6"
      define_method(:install) do
        bin.install "nomatron-agent"
      end
    end
  end

  test do
    system "#{bin}/nomatron-agent", "-h"
  end
end
